### ISSUE TITLE
Empty views.py file

### ISSUE THREAD

**Issue by mord4z** [Pawamoy/django-suit-dashboard#13]
Installing with pip install django-suit-dashboard give me a empty views.py file

**Comment by Pawamoy** [comment]
Yes, I'm sorry, pypi and github versions are not synced. I'll try to update them all later today ! I'll keep you in touch. You can still install it with pip's `-e` option but I agree it's not great.

**Comment by Pawamoy** [comment]
Hey, so I updated the PyPi version to 1.0.0 (major update since many things changed), but please keep in mind that it is very recent code, it's not mature, and we can consider it a beta !

Documentation is now on the wiki (previously on ReadTheDocs).

Pull requests are very welcomed though, and issues too :)
